@url = https://8080-diegomunhoz-sw02104bgam-p9g5v34n9d8.ws-us116.gitpod.io

GET {{url}}/plataformas

###
POST {{url}}/plataformas
Content-Type: application/json

{
    "nome": "XBOX Series S"
}

###
DELETE {{url}}/plataformas/1

###
PUT {{url}}/plataformas/3a
Content-Type: application/json

{
    "nome": "XBOX Series X"
}